import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "../fonts/Poppins-Light.ttf",
  variable: "--font-light",
});
const geistMono = localFont({
  src: "../fonts/Poppins-Regular.ttf",
  variable: "--font-regular",
});

const fontBold = localFont({
  src: "../fonts/Poppins-SemiBold.ttf",
  variable: "--font-semibold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}   ${fontBold.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
